### PR TITLE
Translation for Portuguese - 2.x

### PR DESCRIPTION
**Pull request by tavaresgerson**

### CODE REVIEW

**Comment by markstory** [comment]
Thanks for getting this started. I will get it merged as soon as I have time to get deployments updated for this translation.

**Comment by dereuromark** [comment]
Is this really useful/helpful?
These kinf of docs are soon outdated and lying and will cause more harm down the road.
Especially for small plugins like these that have even a way lower maintainer number than the core framework package(s) itself.

**Comment by markstory** [comment]
I think complete translations are helpful. Duplicating the english docs is not as helpful as they will not ever be maintained and may set future translators off with stale information.

**Comment by ADmad** [comment]
Unless all pages are translated I am not in favor of merging this. People's initial gusto soon wears off as they get busy / lost interest and incomplete translations almost always remain incomplete.

**Comment by tavaresgerson** [comment]
I'am compromised translate this documentation, the cakephp and other plugins is part for my jobs and my too collegues. Is not entusiasm

**Comment by dereuromark** [comment]
Given that this is incomplete and no further activity for a year, we can close this.
The topic is difficult to keep up to date anyway, since the primary language (EN) is also constantly updated.

**Pull request closed without merging**
