### PR TITLE
Correct PHP requirement

### PR DESCRIPTION
**Pull request by ravage84**
According to https://github.com/cakephp/authorization/releases/tag/2.3.0

> Authorization 2.3.0 requires at least CakePHP 4.4.0 and PHP 7.4

### CODE REVIEW

**Comment by ADmad** [comment]
The test suite ran fine on PHP 7.2 https://github.com/cakephp/authorization/actions/runs/3789799126/jobs/6443887879.

So not sure if the release description is accurate.

**Comment by othercorey** [comment]
The cake versions weren't updated either so something's amiss.

**Comment by markstory** [comment]
Could be that I conflated authentication & authorization and thought that both of them had dependency updates. I think our best course of action is to update the release notes instead of changing the code. Unless we want to start pruning old PHP versions as we build towards 5.x

**Comment by othercorey** [comment]
Let's do that. I'd rather not restrict plugins until needed.

**Comment by ADmad** [comment]
I have updated the release notes.

**Pull request closed without merging**
