### PR TITLE
Feature: BeforeScopeInterface (2.x)

### PR DESCRIPTION
**Pull request by jamisonbryant**
See https://github.com/cakephp/authorization/pull/260/ for a detailed description.

This PR contains the same changes for the 2.x branch (CakePHP v4) branch.

## Checklist

- [x] Tests written and passing
- [x] Code follows coding standards
- [x] Documentation updated if necessary
- [x] Spelling/grammar check done

### CODE REVIEW

**Comment by jamisonbryant** [comment]
The two stan failures are for `src/Identity.php` which is not a file I touched. It looks like Psalm wants me to expand the return types, but I'm not sure if I should do that since it's unrelated to the changes made in this PR.

Any suggestions what I should do? All the other checks pass.

**Comment by ADmad** [comment]
Please rebase your changes on the 2.next branch.

New features need to target The x.next branches as they require new minor releases.

**Comment by jamisonbryant** [comment]
@ADmad I think I did it, but I'm not so familiar with doing rebases on a fork. Does it look right now?

**Comment by jamisonbryant** [comment]
Closing, will attempt to recreate and hope that cleans up the commits.

**Pull request closed without merging**
